// <auto-generated />
namespace BBBHackton.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dgsg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dgsg));
        
        string IMigrationMetadata.Id
        {
            get { return "201711091335143_dgsg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
